### ISSUE TITLE
level-party compatibility

### ISSUE THREAD

**Issue by vespakoen** [mattstyles/level-promisify#1]
Hey Matt!

Thanks for the library, it looks great!
I am trying to integrate it in a project where I need multiple connections to the leveldb instance.
For this, I am using substack's **level-party**

Do you know how I could integrate the 2?

Thanks!

**Comment by mattstyles** [comment]
Hey, good to hear its getting some use!

I've no idea but it's something I'm keen to explore.

I've just written [levelable](https://github.com/mattstyles/levelable) which merges multilevel and sublevels but I think level-party maybe obsoletes it! ha ha! so many modules!

On my todo list is actually to update this library, I'm a bit slammed for a few weeks but I'll definitely try and have a play and look at level-party and see if we can get something going using them together

**Comment by mattstyles** [comment]
Hey

So, I did have a quick look at this, I think the fix is going to be pretty simple. I've opened up a v2 branch and dumped a dummy commit in there that will use an existing db if passed in at creation (its a dirty check at present but I just want to see how well it works) and that seems to work, I've got these two processes running at the same time with no probs

```
var party = require( 'level-party' );
var promisify = require( './index.js' );
var db = party( '/tmp/my.db', { encoding: 'json' } );
var p = promisify( db, { sync: true } );

p.put( 'test', 'hello promises' )
    .catch( function( err ) {
        console.error( err );
    });
```

```
var party = require( 'level-party' );
var promisify = require( './index.js' );
var db = party( '/tmp/my.db', { encoding: 'json' } );
var p = promisify( db, { sync: true } );

p.get( 'test' )
    .then( function( res ) {
        console.log( res );
    })
    .catch( function( err ) {
        console.error( err );
    });
```

There a few (quite a few) other things I want to tidy up but being able to pass in any leveldb should be a key thing for v2. infact, there's really no need for level-promisify to create anything, it should just expose some convenience methods for accessing the underlying db.

**Comment by vespakoen** [comment]
Hey, I just stumbled upon this issue by "accident", thanks for taking the time to figure this out!
I must have missed the comment.
